
name: Convert MANRS Docs to PDF and HTML
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'markdown/**.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: markdown
          output_dir: pdf
          images_dir: markdown/media
          # for example <img src="./images/file-name.png">
          image_import: media
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v1
        with:
          name: pdf
          path: pdf/*.pdf

  converttohtml:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: markdown
          output_dir: html
          images_dir: markdown/media
          # for example <img src="./images/file-name.png">
          image_import: media
          # Default is true, can set to false to only get PDF files
          build_pdf: false
      - uses: actions/upload-artifact@v1
        with:
          name: html
          path: html/*.html